jaffle_shop_iceberg:
  outputs:
    dev:
      type: trino
      host: 172.80.0.80
      port: 8080
      user: cagri
      catalog: jaffle_shop_iceberg
      schema: jaffle_shop_sc
  target: dev

jaffle_shop_postgres:
  outputs:
    dev:
      type: postgres
      host: 172.80.0.10
      port: 5432
      user: cagri
      password: '3541'
      dbname: jaffle_shop_postgres
      schema: jaffle_shop_sc
  target: dev